site_name: retest docs

theme:
  name: material
  custom_dir: "theme"
  favicon: "assets/images/favicon.ico"
  icon:
    logo: "retest/logo"
    repo: "fontawesome/brands/github"
  features:
    - tabs

extra_css:
  - "assets/stylesheets/colors.css"

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - redirects:
      redirect_maps:
        # Official redirects
        "code-of-conduct.md": "contributing/code-of-conduct.md"
        "contributing.md": "contributing/guidelines.md"
        # Legacy/Moved sites
        "recheck/how-ignore-works-in-recheck.md": "recheck/usage/filter.md"
        "recheck/reuse-golden-master-files.md": "recheck/introduction/usage.md"
        "recheck/properties.md": "recheck/usage/configuration.md"
        "recheck/recheck-options.md": "recheck/usage/configuration.md"
        "recheck/location-of-the-golden-master-files-and-test-reports.md": "recheck/usage/configuration.md"
        "recheck/how-ignore-works.md": "recheck/usage/filter.md"
        "recheck-web/properties.md": "recheck-web/usage/configuration.md"
        "recheck-web/ways-of-using-recheck-web.md": "recheck-web/introduction/usage.md"

repo_name: "retest/docs"
repo_url: "https://github.com/retest/docs"
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/retest"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/retest_en"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/retest-gmbh"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/retest.de"
    - icon: "fontawesome/brands/xing"
      link: "https://www.xing.com/companies/retestgmbh"

nav:
  - Home: index.md
  - Contributing:
      - "Code of Conduct": contributing/code-of-conduct.md
      - "Guidelines": contributing/guidelines.md
      - "contributing/ide-settings.md"
  - recheck:
      - "recheck/introduction/index.md"
      - "recheck/introduction/installation.md"
      - "recheck/introduction/usage.md"
      - "recheck/usage/configuration.md"
      - "recheck/usage/filter.md"
      - "recheck/files/state.md"
      - "recheck/files/report.md"
  - recheck-web:
      - Run your first Test: "recheck-web/run-your-first-test.md"
      - Setup:
          - "recheck-web/setup/maven.md"
      - Tutorial:
          - "recheck-web/tutorial/explicit-checks.md"
          - "recheck-web/tutorial/mvn-execute-locally.md"
          - "recheck-web/tutorial/setup-recheck.ignore.md"
          - "recheck-web/tutorial/using-git-and-github.md"
          - "recheck-web/tutorial/travis-execute-ci.md"
          - "recheck-web/tutorial/upload-test-reports-to-rehub.md"
          - "recheck-web/tutorial/rule-based-ignore.md"
      - "recheck-web/introduction/usage.md"
      - "recheck-web/usage/configuration.md"
      - "recheck-web/element-identification-problem.md"
      - "recheck-web/postpone-test-breakage.md"
      - "recheck-web/unbreakable-selenium.md"
      - "recheck-web/usage/healing.md"
      - "recheck-web/contributor-information.md"
  - recheck.cli:
      - "recheck.cli/setup.md"
      - "recheck.cli/maintain-golden-master.md"
  - review:
      - "review/installation.md"
      - "review/usage/reports.md"
      - "review/usage/healing.md"
